- name: Install Apache and open firewall ports for HTTP traffic
  hosts: all
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Start the Apache service
      service:
        name: apache2
        state: started
    - name: Open the firewall port for HTTP
      ufw:
        rule: allow
        name: 'Apache HTTP'
        port: '80/tcp'
        state: enabled
    - name: Open the firewall port for HTTPS
      ufw:
        rule: allow
        name: 'Apache HTTPS'
        port: '443/tcp'
        state: enabled